# mkdocs.yml
site_name: Tide checking tool documentation

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: true
            members_order: source
            show_source: false
            show_signature: true
            show_signature_annotations: true    
            separate_signature: true

nav:
  - Docs: index.md
  - API Reference: api.md


